# Generated by Django 5.0.7 on 2024-07-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
