# Generated by Django 5.0.7 on 2024-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_content_comment_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AddField(
            model_name='comment',
            name='parentId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
